apiVersion: v1
kind: Service
metadata:
  name: mongo-headless-service
  namespace: databases
  labels:
    app: mongo
  annotations:
    prometheus.io/scrape: "true"   # Разрешаем сбор метрик
    prometheus.io/port: "9216"     # Порт экспортера (не путать с 27017!)
    prometheus.io/path: "/metrics"
spec:
  clusterIP: None
  selector:
    app: mongo
  ports:
  - name: mongodb
    port: 27017
    targetPort: 27017
  - name: metrics
    port: 9216
    targetPort: 9216