apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: mongo
    namespace: databases
spec:
    serviceName: "mongo-headless-service" # ссылка на headless service
    replicas: 2
    selector:
        matchLabels:
            app: mongo
    template:
        metadata:
            labels:
                app: mongo
            annotations:
              prometheus.io/scrape: "true"
              prometheus.io/port: "9216"
              prometheus.io/path: "/metrics"
        spec:
          containers:
          - name: mongo
            image: mongo:8.2
            ports:
            - containerPort: 27017
            env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                  secretKeyRef:
                      name: mongo-creds
                      key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                  secretKeyRef:
                      name: mongo-creds
                      key: password
            livenessProbe:
              exec:
                  command:
                  - mongosh
                  - --eval
                  - "db.adminCommand({ping:1})"
              initialDelaySeconds: 30
              periodSeconds: 10
            readinessProbe:
              exec:
                  command:
                  - mongosh
                  - --eval
                  - "db.adminCommand({ping:1})"
              initialDelaySeconds: 30
              periodSeconds: 5
            volumeMounts:
            - name: mongo-data
              mountPath: /data/db
            - name: mongo-cm-fill-db-script
              mountPath: /docker-entrypoint-initdb.d/fill-db-script.sh # MongoDB автоматически выполнит все .js и .sh файлы
              subPath: fill-db-script.sh
            - name: mongo-cm-init-replicaset
              mountPath: /docker-entrypoint-initdb.d/init-replicaset.sh
              subPath: init-replicaset.sh  # Важно!
          
          - name: mongo-exporter
            image: percona/mongodb_exporter:0.50
            ports:
              - containerPort: 9216
                name: metrics
            envFrom:
              - secretRef:
                  name: mongo-creds
            env:
              - name: MONGO_INITDB_ROOT_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: mongo-creds
                    key: username
              - name: MONGO_INITDB_ROOT_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: mongo-creds
                    key: password
              - name: MONGODB_URI
                value: "mongodb://$(MONGO_INITDB_ROOT_USERNAME):$(MONGO_INITDB_ROOT_PASSWORD)@127.0.0.1:27017"
            args: ["--collect-all", "--compatible-mode"]          
            livenessProbe:
              tcpSocket:
                port: 9216
              initialDelaySeconds: 60
              periodSeconds: 10
            readinessProbe:
              tcpSocket:
                port: 9216
              initialDelaySeconds: 40
              periodSeconds: 5
            resources:
              requests:
                memory: "256Mi"
                cpu: "200m"
              limits:
                memory: "512Mi"
                cpu: "400m"
          
          volumes:
          - name: mongo-cm-fill-db-script
            configMap:
              name: mongo-cm-fill-db-script
              defaultMode: 0755  # Добавить права на выполнение
          - name: mongo-cm-init-replicaset
            configMap:
              name: mongo-cm-init-replicaset
              defaultMode: 0755  # Добавить права на выполнение

    volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi